### ISSUE TITLE
Major issues

### ISSUE THREAD

**Issue by Pixeluted** [atrexus/vulkan#4]
1. Loading this in Binary Ninja will fail to find anything (Only works on IDA)
2. XREFs  seems to be not working, because getting a normal dump (from scylla for example) will give you XREF to "Video Recording Started", not here. It does have more functions than the scylla dump but XREFs seems to be broken

**Comment by atrexus** [comment]
Thanks for the observation, my last commit was s mistake. I basically destroys all xrefs like you said as well as other code. I will push another change that should fix this. One thing I can't wrap my head around was why IDA was crashing. Sorry for the issues.

**Comment by atrexus** [comment]
I added a fix and tested on the latest version on Roblox (I used IDA to analyze this time).
