### ISSUE TITLE
Weird issues

### ISSUE THREAD

**Issue by KRASN0VVV** [atrexus/vulkan#7]
Cool project, I read through the source code. Why are you using nop instead of int3s? It will cause a lot of issues when IDA does analysis on the functions and starts bridging them

Do you also plan on adding a feature where you can fix the IAT, fix the stubbed branches etc.. ?  😁

**Comment by atrexus** [comment]
I'm not really aware of any issues regarding `nop` instructions. Dumps load fine in IDA and Binary Ninja. 

Fixing the IAT will be annoying but I could look into it. Same with the stubbed branches.

**Comment by nirmitSIXTEEN** [comment]
![image](https://github.com/user-attachments/assets/529423bd-45bb-46a8-b85f-fa9446a2acd6)
truly a THUNK moment

**Comment by nirmitSIXTEEN** [comment]
![image](https://github.com/user-attachments/assets/a735b81c-651a-45e9-8aca-735d39fa9e75)

**Comment by atrexus** [comment]
Whoops... I accidentally merged a branch I shouldn't have into main.

**Comment by atrexus** [comment]
I have added support for the import directory in the latest commit. Please check [v2.0.0](https://github.com/atrexus/vulkan/releases/tag/v2.0.0).
